# Generated by Django 3.0.5 on 2020-04-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogContent',
            new_name='blogDescription',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogDate',
            new_name='date',
        ),
    ]
